# joint_limit: 関節の可動範囲．記入しない場合は無限回転可能とみなす
# offset: ロボット起動時（原点出し時）の位置と，実際のロボットのゼロ点位置との差（デジタル値）

motor_list:
  Hip:  # Joint name
    can_id: 1 
    model: AK10-9
    Kp: 20.0  # Pゲイン初期値
    Kd: 1.0   # Dゲイン初期値
    offset: 70.7  # モータのゼロ点合わせ位置と実際のゼロ点との差（符号注意！）[deg]
    joint_limit: [-90.0, 90.0] # 関節可動角[deg]．ソフトウェア上で関節制限を行うため．
    inverseDirection: true      # モータの回転方向とロボットの回転方向が逆の場合はtrueに設定！